Environment Optimization
CarperAI/nmmo-environment pull request #86
Opened 2023-06-28 01:55 UTC by MarkHaoxiang

Some low hanging fruit to optimize the environment. With low population counts, up to 50% faster.

2023-06-28 02:36 UTC, kywch commented
Thanks, Mark! There seems to be many changes here and there, so allow me to take a careful look.

2023-06-29 06:22 UTC, kywch requested changes
Thank you for making npcs much faster, Mark! The test I've been using confirms the speed up.

```python
from nmmo.task.task_api import nmmo_default_task
from tests.testhelpers import profile_env_step

# nmmo.config.Default() setting: 128 agents
tasks = nmmo_default_task(range(128))
profile_env_step(tasks=tasks)
```

The 2.0 branch:
```
 - env.step({}): 5.237950573999115
 - env.realm.step(): 1.8601984710003308
 - env._compute_observations(): 0.6015106539998669
 - obs.to_gym(), ActionTarget: 0.958669548999751
 - env._compute_rewards(): 0.8221662120013207
```

The current branch:
```
 - env.step({}): 4.958883338000305
 - env.realm.step(): 1.3220626919974166   <-- YAY
 - env._compute_observations(): 0.5937297150012455
 - obs.to_gym(), ActionTarget: 0.9411229560028005
 - env._compute_rewards(): 0.9482983250018151
```

However, removing the game state indices, caches seem to hurt the performance, when tested with 128 players and 128 npcs, the numbers we use in the competition. Can you please confirm if the game state-related changes are necessary?

Thank you.

2023-06-29 06:22 UTC, kywch commented on nmmo/core/map.py
> +        self.habitable_tiles[r, c] = tile.habitable
nice!

2023-06-29 06:22 UTC, kywch commented on nmmo/systems/ai/move.py
> +# pylint: disable=E1136
please change to the error category (the same for the first line)

2023-06-29 06:22 UTC, kywch commented on nmmo/systems/ai/move.py
> +def habitable(realm_map, ent, np_random):
how much speed do we gain by changing `np_random.choice(cands)` to below? 

also, would it change a lot if we replace habitable with random_safe?

2023-06-29 06:22 UTC, kywch commented on nmmo/systems/ai/utils.py
>  def lInf(ent, targ):
can we also get rid of this function?

2023-06-29 06:22 UTC, kywch commented on nmmo/systems/ai/utils.py
> +      'foilage', 'water') and lInfty(ent.pos, tile.pos) <= rng
can we use `utils.linf_single` here? 

there are several distance functions defined, so it'd be great if we can remove redundant ones

2023-06-29 06:22 UTC, kywch commented on nmmo/systems/ai/utils.py
> +   if (start,goal) in realm_map.pathfinding_cache:
nice!

2023-06-29 06:22 UTC, kywch commented on tests/test_optimization.py
> +# Test invariants assumed for certain optimizations
please move this test file to `tests/core/test_immutable_tile_property.py` and rename accordingly

2023-06-29 10:14 UTC, kywch commented
Here is another test case to optimize, simulating complex tasks, touching all entity, item, and event data. 

```python
  from nmmo.task.task_api import nmmo_default_task, make_same_task
  from nmmo.task.base_predicates import CountEvent, FullyArmed
  from nmmo.systems.skill import Melee
  from tests.testhelpers import profile_env_step

  # nmmo.config.Default() setting: 128 agents
  tasks = nmmo_default_task(range(128))
  tasks += make_same_task(CountEvent, range(128),
                          pred_kwargs={'event': 'EAT_FOOD', 'N': 10})
  tasks += make_same_task(FullyArmed, range(128),
                          pred_kwargs={'combat_style': Melee, 'level': 3, 'num_agent': 1})
  profile_env_step(tasks=tasks)
```

2.0 branch
```
 - env.step({}): 9.356640450998384
 - env.realm.step(): 1.9452383820025716
 - env._compute_observations(): 0.6063221270014765
 - obs.to_gym(), ActionTarget: 0.9888858630001778
 - env._compute_rewards(): 4.478575074994296
```

this branch
```
 - env.step({}): 9.688806402999035
 - env.realm.step(): 1.4039403799979482
 - env._compute_observations(): 0.606985855003586
 - obs.to_gym(), ActionTarget: 0.998996601003455
 - env._compute_rewards(): 5.417658225997002
```

As the (training) task becomes complex, computing rewards takes so much time. This certainly is a big, separate target for optimization, after merging in the nice gains in this PR.

2023-06-29 10:37 UTC, kywch commented
With a custom function that combines StayAlive, CountEvent, FullyArmed

```python
  from nmmo.task.task_api import nmmo_default_task, make_same_task
  from nmmo.task.base_predicates import StayAlive, CountEvent, FullyArmed
  from nmmo.systems.skill import Melee
  from tests.testhelpers import profile_env_step

  def complex_task(gs, subject, event, N, combat_style, level, num_agent):
    return StayAlive(gs, subject) * CountEvent(gs, subject, event, N) * \
           FullyArmed(gs, subject, combat_style, level, num_agent)

  # nmmo.config.Default() setting: 128 agents
  tasks = make_same_task(complex_task, range(128),
                         pred_kwargs={'event': 'EAT_FOOD', 'N': 10,
                                      'combat_style': Melee, 'level': 3, 'num_agent': 1})
  profile_env_step(tasks=tasks)
```

2.0 branch
```
 - env.step({}): 8.587407042999985
 - env.realm.step(): 1.891514784998435
 - env._compute_observations(): 0.5926610509995953
 - obs.to_gym(), ActionTarget: 0.9907544480010984
 - env._compute_rewards(): 3.858267388000968
```

this branch
```
 - env.step({}): 8.907805581999128
 - env.realm.step(): 1.369155314998352
 - env._compute_observations(): 0.5924305849985103
 - obs.to_gym(), ActionTarget: 0.9765266709946445
 - env._compute_rewards(): 4.661505613999907
```

2023-07-03 02:12 UTC, kywch commented
Thank you, Mark! I see that the hash patch brought some performance gains in the same `complex_task()` test. Nice job!

```
 - env.step({}): 7.718032001999745
 - env.realm.step(): 1.3791717379999682
 - env._compute_observations(): 0.597285723999903
 - obs.to_gym(), ActionTarget: 0.9713346349999483
 - env._compute_rewards(): 3.569329479999851     VS. 3.858267 (before the hash patch)
```

I agree that the tidying up distance functions, etc, would be better as a separate PR. However, I still have an issue with the `habitable()` function in this PR so cannot move forward without good justification. Thank you.

2023-07-04 03:02 UTC, kywch commented
Thanks Mark for making the changes! I agree that the new `habitable()` function is much faster by using `np_random.intergers()` and the cached `habitable_tiles`. However, I think it can be made more readable. For example,

```python
    DIRECTIONS = [ # row delta, col delta, action
        (-1, 0, action.North),
        (1, 0, action.South),
        (0, -1, action.West),
        (0, 1, action.East)]

    def habitable_short(realm_map, ent, np_random):
      r, c = ent.pos
      is_habitable = realm_map.habitable_tiles
      start = np_random.integers(4)
      for i in range(4):
        print((start + i) & 3)
        # Use bitwise AND to loop through directions
        dr, dc, act = DIRECTIONS[(start + i) & 3]
        if is_habitable[r + dr, c + dc]:
          return act

      return action.North
```

2023-07-04 11:18 UTC, MarkHaoxiang commented
@kywch  Thanks for the suggestion! I have tested and your version seems to have the same performance while being more readable. The corresponding changes have been applied.

2023-07-04 12:41 UTC, kywch commented
Thank you for your work, Mark! I'm happy to merge this PR to 2.0

2023-07-04 12:41 UTC, kywch approved these changes

2023-07-04 12:42 UTC, merged